#cloud-config
users:
  - name: devops
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7E75JwR78Zj0AGf0Hk9VqAs9e37+yOPNNssEdbHM3Uh15BvoHqDTfr8zRO3OsiWBeFmIR0KH8qdwraj1DGGsvnDAwDbi1mQH6V4e/9U269oBFJWKiLAxLUStyRGwK2EZOJvKjT6coic0Hck6I+LUp8QQRMZT8B4UJVk6N4nq0bg0v23dGUm6ULfrMHdJlLGde8Eb+ln/CWjOQXP/4G2UAOGi5PLlftqqJnqsGDS+MfCmNofifjq6NnF65i9JWkrfEVye3Ny3jwEEkBOaojtv9atjE+ExCsmH2BbJYAjEKNjamQwJkJ4iteGZEm88JCOkzRDr0ZEbgac4l7snbRTWt+2rz0UFnzYj00iAnrvQRh1OGgopspSZr7VJEvqdajO24PB7EuNVhG/y4mCpQ7ui1zFLF7X8s1/l6BXuCquiMOtldas5WzgAi1BiyOY3dj6iSEiR182asOsv/VRmmoQGIWQWU1qDQ7fvNCr+qKqSllslkJDb1MMgUumRiCKUI2VrdHt2tKuoHIKxR3zrHAhRe7gDCokPACFUcqOwL6wgFhtqtKJ1EzVl8yQBngnmaPDH/VGUHFhWU6i13hW76B1I/hhdI670l0YyJlsscxpBzWtHlgqTRzNX0l9LpWZhBXkKMluAH0JVy1fOfOs/zHJwqEkCmdDQyuuzN0z/B4PCCGQ== renanssilva@MacBook-Pro.local
package_update: true
package_upgrade: true
packages:
  - git
  - vim
  - neovim
  - gnupg
  - redis-server
runcmd:
  - cd /home/devops
  - touch I_WAS_HERE
  - echo "sudo tail -f -n25 /var/log/cloud-init-output.log" > ./tail_log.sh
  - echo "sudo less /var/log/cloud-init-output.log" > ./less_log.sh
  - echo "started runcmd" >> /var/log/bootstrap

    # redis
    # FIXME: Add basic redis auth here
  - echo "protected-mode no" > /etc/redis/redis.conf
  - systemctl restart redis
  - echo "finished settingup redis" >> /var/log/bootstrap

    # mongo
  - wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list
  - apt-get update
  - apt-get install -y mongodb-org
  - echo "finished installing mongo" >> /var/log/bootstrap

    # rabbitmq
  - wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | apt-key add -
  - echo "deb https://packages.erlang-solutions.com/ubuntu focal contrib" | tee /etc/apt/sources.list.d/rabbitmq.list
  - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | bash
  - apt-get update
  - apt-get install -y rabbitmq-server --fix-missing
  - echo "finished installing rabbitmq-server" >> /var/log/bootstrap

  - echo "[{rabbit,[{loopback_users,[]},{tcp_listeners,[5672]}]}]." > /etc/rabbitmq/rabbitmq.config
  - echo "finished settingup rabbitmq" >> /var/log/bootstrap

  - systemctl restart rabbitmq-server
  - systemctl status rabbitmq-server
  - echo "restarted rabbitmq" >> /var/log/bootstrap
