#cloud-config
users:
  - name: devops
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7E75JwR78Zj0AGf0Hk9VqAs9e37+yOPNNssEdbHM3Uh15BvoHqDTfr8zRO3OsiWBeFmIR0KH8qdwraj1DGGsvnDAwDbi1mQH6V4e/9U269oBFJWKiLAxLUStyRGwK2EZOJvKjT6coic0Hck6I+LUp8QQRMZT8B4UJVk6N4nq0bg0v23dGUm6ULfrMHdJlLGde8Eb+ln/CWjOQXP/4G2UAOGi5PLlftqqJnqsGDS+MfCmNofifjq6NnF65i9JWkrfEVye3Ny3jwEEkBOaojtv9atjE+ExCsmH2BbJYAjEKNjamQwJkJ4iteGZEm88JCOkzRDr0ZEbgac4l7snbRTWt+2rz0UFnzYj00iAnrvQRh1OGgopspSZr7VJEvqdajO24PB7EuNVhG/y4mCpQ7ui1zFLF7X8s1/l6BXuCquiMOtldas5WzgAi1BiyOY3dj6iSEiR182asOsv/VRmmoQGIWQWU1qDQ7fvNCr+qKqSllslkJDb1MMgUumRiCKUI2VrdHt2tKuoHIKxR3zrHAhRe7gDCokPACFUcqOwL6wgFhtqtKJ1EzVl8yQBngnmaPDH/VGUHFhWU6i13hW76B1I/hhdI670l0YyJlsscxpBzWtHlgqTRzNX0l9LpWZhBXkKMluAH0JVy1fOfOs/zHJwqEkCmdDQyuuzN0z/B4PCCGQ== renanssilva@MacBook-Pro.local
package_update: true
package_upgrade: true
packages:
  - git
  - vim
  - neovim
  - gnupg
runcmd:
  - cd /home/devops
  - touch BOOTSTRAP_STARTED
  - echo "sudo tail -f -n25 /var/log/cloud-init-output.log" > ./tail_log.sh
  - echo "sudo less /var/log/cloud-init-output.log" > ./less_log.sh

    # redis
  - add-apt-repository -y ppa:chris-lea/redis-server
  - apt update
  - apt install redis-server -y
  - redis-server --version > /home/devops/redis_version
  - echo PING | redis-cli >> redis_ping
  - echo "ACL SETUSER $(cat /opt/redis_user) allkeys allcommands on >$(cat /opt/redis_passwd)" | redis-cli >> redis_acl
  - echo ACL LIST | redis-cli >> redis_acl
  - echo PING | redis-cli >> redis_ping

    # mongo
  #- wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | apt-key add -
  #- echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-5.0.list
  #- apt update
  #- apt install -y mongodb-org

    # rabbitmq
  - wget -O- https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc | apt-key add -
  - echo "deb https://packages.erlang-solutions.com/ubuntu focal contrib" | tee /etc/apt/sources.list.d/rabbitmq.list
  - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | bash
  - apt update
  - apt install -y rabbitmq-server --fix-missing

  - echo "[{rabbit,[{loopback_users,[]},{tcp_listeners,[5672]}]}]." > /etc/rabbitmq/rabbitmq.config

  - systemctl enable rabbitmq-server
  - systemctl restart rabbitmq-server
  - systemctl status rabbitmq-server
  - rabbitmqctl add_user $(cat /opt/rabbitmq_user) $(cat /opt/rabbitmq_passwd)
  - rabbitmqctl set_user_tags $(cat /opt/rabbitmq_user) administrator
  - rabbitmqctl set_permissions -p / $(cat /opt/rabbitmq_user) ".*" ".*" ".*"

  - touch /home/devops/BOOTSTRAP_DONE
