name: Build Smoke Test

on: push

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup deps
        run: |
          sudo apt install -y libsdl2-dev libsdl2-ttf-dev

      - name: Build
        run: make
